language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable

sudo: false

services:
  - redis-server

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

before_script:
  - mysql -e 'create database travis;'
  - mv .env.travis .env
  - chmod -R 777 storage
  - gulp
  - php artisan key:generate
  - php artisan migrate:refresh --seed
  - php artisan serve >/dev/null 2>&1 &

script: vendor/bin/phpunit

addons:
    code_climate:
        repo_token: 42a378559f5925c6309d5f224743a4136e38d835e62e2e4b40bdf82a7a131344
