haproxy:
  image: eeacms/haproxy
  ports:
   - 80:5000
   - 1936:1936
  env_file: .env.docker
  links:
   - businessstack
  environment:
   - SERVICE_NAMES=businessstack

businessstack:
  image: reflexions/docker-laravel:latest
  env_file: .env.docker
  links:
    - database
    - rabbitmq
    - redis
    - mongodb
    - elasticsearch
  volumes:
    - .:/var/www/laravel

database:
  image: postgres:9.4.4
  env_file: .env.docker
  environment:
    LC_ALL: C.UTF-8

rabbitmq:
  image: rabbitmq
  env_file: .env.docker

redis:
  image: redis
  env_file: .env.docker

mongodb:
  image: mongo
  env_file: .env.docker

elasticsearch:
  image: elasticsearch
  env_file: .env.docker

